export const ALL_PACKAGES = [
  // ── HAJJ ────────────────────────────────────────────────────────────────
  {
    id: 'h1',
    slug: 'hajj-economy-2025',
    category: 'hajj' as const,
    title: 'Hajj Economy Package 2025',
    titleBn: 'হজ্জ ইকোনমি প্যাকেজ ২০২৫',
    price: 580000,
    duration: '40 Days',
    durationBn: '৪০ দিন',
    featured: true,
    imageUrl: '/images/hajj-hero.jpg',
    description:
      'A complete Hajj package for budget-conscious pilgrims. Includes return flights from Dhaka, Makkah & Madinah hotel stays, visa processing, and full guidance from experienced Mutawwif.',
    descriptionBn:
      'বাজেট সচেতন হাজীদের জন্য একটি সম্পূর্ণ হজ্জ প্যাকেজ। ঢাকা থেকে রিটার্ন ফ্লাইট, মক্কা ও মদিনায় হোটেল, ভিসা প্রসেসিং এবং অভিজ্ঞ মুতাওয়াফের তত্ত্বাবধান অন্তর্ভুক্ত।',
    inclusions: [
      'Return air ticket (Dhaka ↔ Jeddah/Madinah)',
      'Makkah hotel — 500m from Haram (25 nights)',
      'Madinah hotel — 300m from Masjid Nabawi (8 nights)',
      'Mina tent accommodation (Aziziyah category)',
      'Visa & government service charge',
      'Ziyarat (Makkah & Madinah)',
      'Experienced Mutawwif & group leader',
      'Airport transfers & Makkah–Madinah coach',
      'Ihram kit & travel bag',
      'Pre-departure training & orientation',
    ],
    itinerary: [
      { day: 'Day 1–2', title: 'Departure from Dhaka', description: 'Group departs from Hazrat Shahjalal International Airport and arrives in Madinah.' },
      { day: 'Day 3–10', title: 'Stay in Madinah', description: 'Prayers at Masjid Nabawi, Ziyarat of historical sites including Masjid Quba, Uhud, and Jannat ul-Baqi.' },
      { day: 'Day 11–12', title: 'Travel to Makkah', description: 'Coach journey to Makkah. Perform Umrah upon arrival.' },
      { day: 'Day 13–35', title: 'Stay in Makkah', description: 'Daily prayers at Masjid al-Haram, preparation for Hajj rituals.' },
      { day: 'Day 36–39', title: 'Hajj Rituals', description: 'Mina, Arafat, Muzdalifah, Jamarat, Tawaf al-Ifadah, Sa\'i, and Tawaf al-Wida.' },
      { day: 'Day 40', title: 'Return to Dhaka', description: 'Depart from Jeddah. Arrive in Dhaka.' },
    ],
  },
  {
    id: 'h2',
    slug: 'hajj-standard-2025',
    category: 'hajj' as const,
    title: 'Hajj Standard Package 2025',
    titleBn: 'হজ্জ স্ট্যান্ডার্ড প্যাকেজ ২০২৫',
    price: 750000,
    duration: '40 Days',
    durationBn: '৪০ দিন',
    featured: false,
    imageUrl: '/images/hajj-hero.jpg',
    description:
      'An upgraded Hajj experience with closer hotel accommodation to Haram, air-conditioned Mina tents, and dedicated group support.',
    descriptionBn:
      'হারামের কাছাকাছি হোটেল, এয়ার কন্ডিশন্ড মিনা তাঁবু এবং ডেডিকেটেড গ্রুপ সহায়তাসহ একটি উন্নত হজ্জ অভিজ্ঞতা।',
    inclusions: [
      'Return air ticket (Dhaka ↔ Jeddah/Madinah)',
      'Makkah hotel — 200m from Haram (25 nights)',
      'Madinah hotel — 150m from Masjid Nabawi (8 nights)',
      'Mina air-conditioned tent (Muaisim category)',
      'Visa & government service charge',
      'Full Ziyarat programme',
      'Dedicated Mutawwif & assistant guide',
      'All ground transfers',
      'Ihram kit, travel bag & accessories',
      'Medical support & first aid kit',
      'Pre-departure training sessions',
    ],
    itinerary: [
      { day: 'Day 1–2', title: 'Departure from Dhaka', description: 'Group departs and arrives in Madinah.' },
      { day: 'Day 3–10', title: 'Stay in Madinah', description: 'Prayers at Masjid Nabawi and comprehensive Ziyarat programme.' },
      { day: 'Day 11–12', title: 'Travel to Makkah', description: 'Premium coach to Makkah. Perform Tawaf and Umrah.' },
      { day: 'Day 13–35', title: 'Stay in Makkah', description: 'Daily Haram prayers and Hajj preparation workshops.' },
      { day: 'Day 36–39', title: 'Hajj Rituals', description: 'Full Hajj rituals with dedicated guide support.' },
      { day: 'Day 40', title: 'Return to Dhaka', description: 'Depart Jeddah. Welcome home ceremony on arrival.' },
    ],
  },
  // ── UMRAH ────────────────────────────────────────────────────────────────
  {
    id: 'u1',
    slug: 'umrah-standard-package',
    category: 'umrah' as const,
    title: 'Umrah Standard Package',
    titleBn: 'উমরাহ স্ট্যান্ডার্ড প্যাকেজ',
    price: 120000,
    duration: '14 Days',
    durationBn: '১৪ দিন',
    featured: true,
    imageUrl: '/images/umrah-placeholder.jpg',
    description:
      'A spiritually enriching 14-day Umrah package covering both Makkah and Madinah with comfortable accommodation and full support.',
    descriptionBn:
      'মক্কা ও মদিনা উভয়ই কভার করা একটি আধ্যাত্মিকভাবে সমৃদ্ধ ১৪ দিনের উমরাহ প্যাকেজ।',
    inclusions: [
      'Return air ticket (Dhaka ↔ Jeddah)',
      'Makkah hotel — 600m from Haram (7 nights)',
      'Madinah hotel — 400m from Masjid Nabawi (5 nights)',
      'Umrah visa',
      'Airport transfers',
      'Makkah–Madinah coach transfer',
      'Ziyarat (Makkah & Madinah)',
      'Group leader & Mutawwif',
      'Ihram kit',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Departure from Dhaka', description: 'Fly from Hazrat Shahjalal International Airport to Jeddah.' },
      { day: 'Day 2–8', title: 'Makkah', description: 'Perform Umrah. Daily prayers at Masjid al-Haram. Ziyarat of Makkah.' },
      { day: 'Day 9–13', title: 'Madinah', description: 'Prayers at Masjid Nabawi. Visit Masjid Quba, Uhud, Jannat ul-Baqi.' },
      { day: 'Day 14', title: 'Return to Dhaka', description: 'Depart from Madinah Airport to Dhaka.' },
    ],
  },
  {
    id: 'u2',
    slug: 'umrah-premium-package',
    category: 'umrah' as const,
    title: 'Umrah Premium Package',
    titleBn: 'উমরাহ প্রিমিয়াম প্যাকেজ',
    price: 180000,
    duration: '21 Days',
    durationBn: '২১ দিন',
    featured: false,
    imageUrl: '/images/umrah-placeholder.jpg',
    description:
      'An extended 21-day premium Umrah experience with 4-star hotels, private transfers, and an extended Madinah stay.',
    descriptionBn:
      '৪-স্টার হোটেল, প্রাইভেট ট্রান্সফার এবং বর্ধিত মদিনা থাকাসহ একটি বিস্তারিত ২১ দিনের প্রিমিয়াম উমরাহ অভিজ্ঞতা।',
    inclusions: [
      'Return air ticket (Dhaka ↔ Jeddah)',
      '4-star Makkah hotel — 200m from Haram (12 nights)',
      '4-star Madinah hotel — 100m from Masjid Nabawi (7 nights)',
      'Umrah visa',
      'Private airport transfers',
      'Luxury coach Makkah–Madinah',
      'Comprehensive Ziyarat',
      'Personal guide & 24/7 support',
      'Ihram kit & travel bag',
      'Laundry service',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Departure from Dhaka', description: 'Fly to Jeddah. Transfer to Makkah hotel.' },
      { day: 'Day 2–13', title: 'Makkah', description: 'Perform Umrah. Extended stay for additional worship and Tawaf.' },
      { day: 'Day 14–20', title: 'Madinah', description: 'Seven blessed nights near Masjid Nabawi. Full Ziyarat programme.' },
      { day: 'Day 21', title: 'Return to Dhaka', description: 'Depart from Madinah to Dhaka.' },
    ],
  },
  // ── TOURS ────────────────────────────────────────────────────────────────
  {
    id: 't1',
    slug: 'dubai-explorer-5nights',
    category: 'tour' as const,
    title: 'Dubai Explorer — 5 Nights 6 Days',
    titleBn: 'দুবাই এক্সপ্লোরার — ৫ রাত ৬ দিন',
    price: 95000,
    duration: '6 Days',
    durationBn: '৬ দিন',
    featured: true,
    imageUrl: '/images/dubai-placeholder.jpg',
    description:
      'Explore the dazzling city of Dubai — Burj Khalifa, Dubai Mall, Desert Safari, and more — in a 6-day fully guided tour.',
    descriptionBn:
      'বুর্জ খলিফা, দুবাই মল, ডেজার্ট সাফারিসহ দুবাইয়ের জমকালো শহর অন্বেষণ করুন — ৬ দিনের সম্পূর্ণ গাইডেড ট্যুরে।',
    inclusions: [
      'Return air ticket (Dhaka ↔ Dubai)',
      '4-star hotel (5 nights)',
      'Airport transfers',
      'Burj Khalifa (At The Top) ticket',
      'Dubai City Tour',
      'Desert Safari with BBQ dinner',
      'Dubai Mall & Fountain show',
      'Abu Dhabi day trip',
      'Travel insurance',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrival in Dubai', description: 'Arrive at Dubai International Airport. Transfer to hotel. Evening at leisure.' },
      { day: 'Day 2', title: 'Dubai City Tour', description: 'Old Dubai (Gold Souk, Spice Souk, Al Fahidi), Jumeirah Mosque, Burj Al Arab photo stop.' },
      { day: 'Day 3', title: 'Burj Khalifa & Dubai Mall', description: 'Burj Khalifa At The Top experience. Evening Dubai Mall & Fountain Show.' },
      { day: 'Day 4', title: 'Desert Safari', description: 'Afternoon dune bashing, camel ride, henna painting, BBQ dinner under the stars.' },
      { day: 'Day 5', title: 'Abu Dhabi Day Trip', description: 'Sheikh Zayed Grand Mosque, Corniche, Ferrari World (exterior). Return to Dubai.' },
      { day: 'Day 6', title: 'Departure', description: 'Free morning shopping at Dubai Mall. Transfer to airport. Return to Dhaka.' },
    ],
  },
  {
    id: 't2',
    slug: 'malaysia-7nights',
    category: 'tour' as const,
    title: 'Malaysia Magic — 7 Nights 8 Days',
    titleBn: 'মালয়েশিয়া ম্যাজিক — ৭ রাত ৮ দিন',
    price: 85000,
    duration: '8 Days',
    durationBn: '৮ দিন',
    featured: false,
    imageUrl: '/images/malaysia-placeholder.jpg',
    description:
      'Experience the best of Malaysia — Kuala Lumpur\'s iconic skyline, Genting Highlands, Langkawi beaches, and Batu Caves.',
    descriptionBn:
      'মালয়েশিয়ার সেরাটা অনুভব করুন — কুয়ালালামপুরের আইকনিক স্কাইলাইন, জেন্টিং হাইল্যান্ডস, লাংকাওয়ি সৈকত এবং বাতু গুহা।',
    inclusions: [
      'Return air ticket (Dhaka ↔ Kuala Lumpur)',
      '4-star hotel (7 nights)',
      'Airport transfers',
      'KL City Tour with Petronas Twin Towers',
      'Genting Highlands day trip',
      'Langkawi Island 2-day trip',
      'Batu Caves visit',
      'Travel insurance',
      'Visa assistance',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrival in Kuala Lumpur', description: 'Arrive at KLIA. Transfer to hotel in KL city centre.' },
      { day: 'Day 2', title: 'Kuala Lumpur City Tour', description: 'Petronas Twin Towers, KLCC Park, KL Tower, Merdeka Square, Central Market.' },
      { day: 'Day 3', title: 'Genting Highlands', description: 'Cable car ride to Genting Highlands. Casino resort, theme park, and cool mountain air.' },
      { day: 'Day 4–5', title: 'Langkawi Island', description: 'Ferry to Langkawi. Eagle Square, Cable Car, Sky Bridge, Underwater World, island beaches.' },
      { day: 'Day 6', title: 'Return to KL', description: 'Ferry back to KL. Free evening for shopping at Bukit Bintang.' },
      { day: 'Day 7', title: 'Batu Caves & Putrajaya', description: 'Morning Batu Caves. Afternoon Putrajaya government complex & Botanical Gardens.' },
      { day: 'Day 8', title: 'Departure', description: 'Transfer to KLIA. Return flight to Dhaka.' },
    ],
  },
  {
    id: 't3',
    slug: 'thailand-6nights',
    category: 'tour' as const,
    title: 'Thailand Treasure — 6 Nights 7 Days',
    titleBn: 'থাইল্যান্ড ট্রেজার — ৬ রাত ৭ দিন',
    price: 80000,
    duration: '7 Days',
    durationBn: '৭ দিন',
    featured: false,
    imageUrl: '/images/thailand-placeholder.jpg',
    description:
      'Bangkok temples, Pattaya beaches, Coral Island, and the vibrant Thai night markets — all in one unforgettable week.',
    descriptionBn:
      'ব্যাংকক মন্দির, পাতায়া সৈকত, কোরাল আইল্যান্ড এবং থাইল্যান্ডের প্রাণবন্ত নাইট মার্কেট — এক অবিস্মরণীয় সপ্তাহে।',
    inclusions: [
      'Return air ticket (Dhaka ↔ Bangkok)',
      '4-star hotel (6 nights)',
      'Bangkok–Pattaya transfer',
      'Bangkok City Tour (Temples & Grand Palace)',
      'Coral Island speed boat trip',
      'Alcazar Cabaret Show (Pattaya)',
      'Safari World & Marine Park (Bangkok)',
      'Airport transfers',
      'Travel insurance',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrival in Bangkok', description: 'Arrive at Suvarnabhumi Airport. Check in to Bangkok hotel.' },
      { day: 'Day 2', title: 'Bangkok City Tour', description: 'Grand Palace, Wat Phra Kaew, Wat Pho, Wat Arun, Chao Phraya river cruise.' },
      { day: 'Day 3', title: 'Safari World', description: 'Drive-through Safari Park and Marine Park with dolphin & seal shows.' },
      { day: 'Day 4', title: 'Pattaya Transfer', description: 'Transfer to Pattaya. Beach Road, Sanctuary of Truth.' },
      { day: 'Day 5', title: 'Coral Island', description: 'Speed boat to Coral Island (Koh Larn). Snorkelling, banana boat, beach lunch.' },
      { day: 'Day 6', title: 'Alcazar & Shopping', description: 'Evening Alcazar Cabaret Show. Pattaya Night Bazaar.' },
      { day: 'Day 7', title: 'Departure', description: 'Return to Bangkok airport. Fly back to Dhaka.' },
    ],
  },
];

export const getPackagesByCategory = (category: 'hajj' | 'umrah' | 'tour') =>
  ALL_PACKAGES.filter((p) => p.category === category);

export const getFeaturedPackages = () =>
  ALL_PACKAGES.filter((p) => p.featured);

export const getPackageBySlug = (slug: string) =>
  ALL_PACKAGES.find((p) => p.slug === slug);
